# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        py36-sqlite:
          TOXENV: py36
          python.version: '3.6'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade tox codecov
        displayName: install tox
      - script: |
          # yarn global add less
          sudo npm install -g less
          lessc --version
        displayName: install less
      - script: |
          npm install yarn
          npm run yarn
        displayName: install node deps
      - script: tox
        displayName: run tox
