version: 2.1

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "poetry.lock" }}
    - run:
        name: install dependencies
        command: |
            sudo apt install yarnpkg
            sudo ln -sf /usr/bin/yarnpkg /usr/bin/yarn
            pip install --user tox codecov "coverage<5"
    - run:
        name: run tox
        command: ~/.local/bin/tox
#    - run:
#        name: upload coverage report
#        command: |
#           if [[ "$UPLOAD_COVERAGE" != 0 ]]; then
#               PATH=$HOME/.local/bin:$PATH
#               coverage xml
#               ~/.local/bin/codecov --required -X search gcov pycov -f coverage.xml --flags $CIRCLE_JOB
#           fi
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "poetry.lock" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          - TOXENV=lint
          - UPLOAD_COVERAGE=0
  py37:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37
  py38:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38
  py39:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV=py39

workflows:
  version: 2
  test:
    jobs:
      - lint
      - py37
      - py38
      - py39
